version: "3.9"
services:
  api:
    build: ../
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    env_file: ../.env
    depends_on: [db]
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: recoveryos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
volumes:
  pgdata:
