[tool.black]
line-length = 100
target-version = ["py311", "py312"]
exclude = "/(venv|.venv|dist|build|__pycache__)/"

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = ["venv", ".venv", "dist", "build", "__pycache__"]

[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = ["venv", ".venv", "dist", "build", "__pycache__"]
select = ["E", "F", "I"]
ignore = ["E203", "E266"]

[tool.ruff.lint.isort]
known-first-party = ["recoveryos"]
