[tool.black]
line-length = 120
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 120
py_version = 311

[tool.ruff]
line-length = 120
target-version = "py311"
select = ["E", "F", "I"]
ignore = []
per-file-ignores = { 
  "recoveryos_rooted/**" = ["E501", "I001", "E401", "F401", "F841"],
  "risk*.py" = ["E501", "I001", "E401", "F841"],
  "coping.py" = ["E501"],
  "rag.py" = ["E501", "I001", "F841"],
  "db.py" = ["I001"],
  "main.py" = ["E501", "I001", "F401", "F841"],
  "scripts/openai_provider_test.py" = ["I001"],
  "test_api.py" = ["I001"],
  "users.py" = ["I001"],
  "tools.py" = ["I001"]
}
