name: Build & Container Scan (push)

on:
  push:
    branches: [ "main" ]          # publish only on main
  workflow_dispatch:               # allow manual publish runs


permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

concurrency:
  group: ghcr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Prune Docker
        run: |
          docker system prune -af || true
          docker builder prune -af || true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/recoveryos
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
          labels: |
            org.opencontainers.image.title=RecoveryOS
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

- name: Build and push
  uses: docker/build-push-action@v6
  with:
    context: .
    push: true                      # always push on main/manual
    tags: ${{ steps.meta.outputs.tags }}
    labels: ${{ steps.meta.outputs.labels }}
    cache-from: type=gha
    cache-to: type=gha,mode=max

# Optional Trivy image scan (non-blocking)
- name: Trivy scan (image)
  uses: aquasecurity/trivy-action@0.24.0
  with:
    scan-type: image
    image-ref: ghcr.io/${{ github.repository }}:latest
    format: sarif
    output: trivy-results.sarif
    scanners: vuln
  continue-on-error: true

- name: Check SARIF exists
  id: sarif-image
  run: |
    if [ -f trivy-results.sarif ]; then echo "exists=true" >> "$GITHUB_OUTPUT"; fi

- name: Upload SARIF (Trivy)
  if: ${{ steps.sarif-image.outputs.exists == 'true' }}
  uses: github/codeql-action/upload-sarif@v3
  with:
    sarif_file: trivy-results.sarif


