name: Build lockfile

on:
  push:
    paths: [ "requirements.txt" ]
  workflow_dispatch:

jobs:
  lock:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pip-tools
        run: python -m pip install -U pip pip-tools

      - name: Remove old lockfile (if any)
        run: git rm -f requirements.lock.txt || true

      - name: Generate requirements.lock.txt with hashes
        run: |
          if [ -f requirements.base.in ]; then
            pip-compile --generate-hashes -o requirements.lock.txt requirements.base.in
          else
            pip-compile --generate-hashes -o requirements.lock.txt requirements.txt
          fi

      - name: Sanity check (must contain sha256 hashes)
        run: grep -q -- "--hash=sha256:" requirements.lock.txt

      - name: Commit lockfile
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add requirements.lock.txt
          git commit -m "chore(deps): regenerate requirements.lock.txt" || echo "No changes"
          git push || true

