name: Main Build & Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_container_scan:
    name: Build & Container Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Prune Docker
        run: |
          docker system prune -af || true
          docker builder prune -af || true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/recoveryos
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
          labels: |
            org.opencontainers.image.title=RecoveryOS
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trivy scan (image)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: image
          image-ref: ghcr.io/${{ github.repository_owner }}/recoveryos:latest
          format: sarif
          output: trivy-results.sarif
          scanners: vuln
        continue-on-error: true

      - name: Check SARIF exists
        id: sarif-image
        run: |
          if [ -f trivy-results.sarif ]; then echo "exists=true" >> "$GITHUB_OUTPUT"; fi

      - name: Upload SARIF (Trivy)
        if: ${{ steps.sarif-image.outputs.exists == 'true' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Enforce HIGH+ failure on main
        if: steps.trivy.outcome != 'success'
        run: |
          echo "Trivy reported CRITICAL/HIGH issues on main"
          exit 1
