name: Main CI & Publish (GHCR)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

concurrency:
  group: build-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preflight-lock:
    name: Preflight · lockfile freshness (blocking)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install 'pip==24.2.1' 'pip-tools==7.4.1'
      - run: |
          pip-compile --quiet --generate-hashes -o /tmp/requirements.lock.txt requirements.txt
      - run: |
          awk '!/^\s*#/' requirements.lock.txt > /tmp/current.txt
          awk '!/^\s*#/' /tmp/requirements.lock.txt > /tmp/new.txt
          set -e
          if ! diff -u /tmp/current.txt /tmp/new.txt > /tmp/lock.diff; then
            echo "::error file=requirements.lock.txt::Lockfile is stale relative to requirements.txt"
            cat /tmp/lock.diff || true
            exit 1
          fi

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: preflight-lock
    env:
      PYTHONDONTWRITEBYTECODE: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install -U pip
          python -m pip install --require-hashes -r requirements.lock.txt
          python -m pip install -U ruff
      - run: ruff format --check .
      - run: ruff check .
      - run: chmod +x scripts/*.sh || true
      - run: |
          if [ -d tests ]; then
            python -m pip install -U pytest
            pytest -q
          else
            echo "No tests/ directory; skipping."
          fi
      - run: bash scripts/smoke.sh

  docker-publish:
    name: Docker Build & Push → GHCR
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - run: echo "IMAGE=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:main
            ${{ env.IMAGE }}:sha-${{ github.sha }}

  security:
    name: Security Scans (blocking on main)
    runs-on: ubuntu-latest
    needs: docker-publish
    steps:
      - uses: actions/checkout@v4
      - run: echo "IMAGE=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --redact --verbose
      - continue-on-error: true
        run: |
          docker run --rm \
            -v "$PWD":/work \
            aquasec/trivy image --security-checks vuln \
            --format sarif --output trivy-image.sarif \
            --severity HIGH,CRITICAL ${{ env.IMAGE }}:sha-${{ github.sha }} || true
      - if: ${{ always() && hashFiles('trivy-image.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
      - run: |
          docker run --rm aquasec/trivy image --security-checks vuln \
            --exit-code 1 --severity HIGH,CRITICAL \
            ${{ env.IMAGE }}:sha-${{ github.sha }}
