name: OpenAI Smoketest

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoketest:
    runs-on: ubuntu-latest
    # keep this non-blocking
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps (best effort)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install "openai>=1.40.0" || true

      - name: Run smoketest (skip if no secret)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "OPENAI_API_KEY not set; skipping smoketest (non-blocking)"; exit 0; fi
          python - <<'PY'
          print("OpenAI smoketest: placeholder OK")
          PY
