name: OpenAI Smoketest

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoketest:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ secrets.OPENAI_API_KEY != '' }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install OpenAI SDK
        run: pip install "openai>=1.40.0"

      - name: Run smoketest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
        run: |
          python scripts/openai_provider_test.py

