name: OpenAI Smoketest

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoketest:
    if: ${{ secrets.OPENAI_API_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (lockfile if present)
        run: |
          python -m pip install -U pip
          if [ -f requirements.lock.txt ]; then
            pip install --require-hashes -r requirements.lock.txt
          else
            pip install -r requirements.txt
          fi

      - name: Run smoketest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/openai_provider_test.py
