name: RecoveryOS Preflight

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dev tooling
        run: |
          pip install ruff==0.4.8 black==24.4.2 isort==5.13.2

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Import sort check (isort)
        run: isort --check-only .

      - name: Lint and syntax check
        run: |
          python -m py_compile $(find . -name "*.py")

      - name: Verify Dockerfile builds
        run: docker build .

      - name: Confirm app starts
        run: |
          if [ -f main.py ]; then
            timeout 30 python -m uvicorn main:app --host 0.0.0.0 --port 8000 &
            sleep 5
            curl -f http://localhost:8000/healthz || (echo "Health check failed" && exit 1)
            pkill -f uvicorn
          fi
