name: Unit & E2E Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # app should degrade gracefully if empty
      PYTHONUNBUFFERED: "1"
      APP_HOST: "127.0.0.1"
      APP_PORT: "8001"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt || true
          pip install "uvicorn[standard]" fastapi pytest pytest-timeout

      - name: Start API (background, no reload)
        run: |
          nohup python -m uvicorn main:app --host "$APP_HOST" --port "$APP_PORT" --no-access-log --log-level info > uvicorn.out 2>&1 &
          echo $! > uvicorn.pid
          sleep 1
          ps aux | grep "[u]vicorn" || true

      - name: Wait for /healthz
        run: |
          for i in $(seq 1 60); do
            code=$(curl -s -o /dev/null -w "%{http_code}" "http://${APP_HOST}:${APP_PORT}/healthz" || true)
            if [ "$code" = "200" ]; then
              echo "Server is up."
              exit 0
            fi
            echo "Waiting for server... ($i/60)"
            sleep 1
          done
          echo "Server did not become healthy in time"
          echo "==== Uvicorn logs (head) ===="
          sed -n '1,200p' uvicorn.out || true
          exit 1

      - name: Run unit tests (no e2e)
        run: |
          pytest -q -m "not e2e" --timeout=180

      - name: Run e2e tests (temporarily non-blocking)
        continue-on-error: true
        run: |
          pytest -q -m "e2e" --timeout=300

      - name: Always dump server logs on failure
        if: failure()
        run: |
          echo "==== Uvicorn logs (tail) ===="
          tail -n 200 uvicorn.out || true
          echo "==== Port usage ===="
          ss -ltnp || true
          echo "==== Processes ===="
          ps aux | grep "[u]vicorn" || true

      - name: Stop server
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then kill -9 $(cat uvicorn.pid) || true; fi

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: uvicorn-logs
          path: uvicorn.out
